<?php
/*******************************************************************************
 *
 *  filename    : /api/1/directory/dump/index.php
 *  last change : 2013-11-10
 *  website     : http;//www.ecc12.com
 *  author      : Cameron King <cking@ecc12.com>
 *  copyright   : Copyright (c) 2013. Cameron King.
 *
 *  COPYING:
 *
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted, provided that the above
 *  copyright notice and this permission notice appear in all copies.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 *  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 *  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 ******************************************************************************/

/**
 * Requires:
 *   ? key=APIKEY         - generated by client, sha1(SECRET . NONCE . TOKEN)
 *   & nonce=NONCE        - generated by client, usually sha1(time() . rand())
 * Returns JSON:
 *   {
 *     result: 1 or 0     - 1 if sucessful, 0 if error
 *     data: [            - empty array on failure, or array of families
 *       {
 *         ...,           - family object
 *       }, ...
 *     ]
 *   }
 */

//Include the function library
require "../../../../Include/Config.php";
require "../../../../Include/Functions.php";

$API_SECRET = "17a4194bdb29b609d39edcc6c3f5c3e781d2068b";
$API_AUTHORIZED = 0;
$API_NEW_TOKEN = 0;
function checkApiKey() {
  $apikey = 0;
  $nonce = 0;
  if(isset($_GET["key"]) && strlen($_GET["key"]) && isset($_SESSION["nonce"]) && strlen($_SESSION["nonce"])) {
    $apikey = $_GET["key"];
    $nonce = $_SESSION["nonce"];
  }
  if($apikey = sha1sum("$API_SECRET$nonce")) {
    $API_AUTHORIZED = 1;
  }
}

header("Content-type: text/x-json");

$response = array(
  'result' => 0,
  'data' => array()
);

checkApiKey();
if(! $API_AUTHENTICATED) {
  print json_encode($response);
  exit;
}

$directorySQL = "select * from `v_directory_report`";
$directoryResults = RunQuery($directorySQL);

$families = array();
while($person = mysql_fetch_object($directoryResults))
{
  if(! isset($families[$person->per_fam_ID]) {
    $families[$person->per_fam_ID] = array(
      "id" => $person->per_fam_ID,
      "name" => $person->fam_Name,
      "people" => array()
    )
  }

  $new_person = array(
    "id" => $person->per_ID,
    "title" => $person->per_Title,
    "firstName" => $person->per_FirstName,
    "middleName" => $person->per_MiddleName,
    "lastName" => $person->per_LastName,
    "suffix" => $person->per_Suffix
  );

  $families[$person->per_fam_ID] = $new_person;
}

$response["result"] = 1;
for($families as $k, $v) {
  $response["data"][] = $v;
}

print json_encode($response);
exit;

